# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '美物心语' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 美物心语

pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'LeanChatLib'
#pod 'LeanCloudSocial'
pod 'MBProgressHUD'
pod 'NAKPlaybackIndicatorView'
pod 'MJExtension'
pod 'LeanCloudSocial'  # 静态库方式引入，依赖 AVOSCloud 库
pod 'MJRefresh'
pod 'UMengSocialCOM' 

               

      target '美物心语Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '美物心语UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
